const sentences = [
	"Surely you didn’t think I was going to keep my filthy Muggle father’s name? No. I fashioned myself a new name, a name I knew wizards everywhere would one day fear to speak, when I became the greatest sorcerer in the world!",
	"My mother died just after I was born, sir. They told me at the orphanage she lived just long enough to name me - Tom after my father, Marvolo after my grandfather.",
	"I can make things move without touching them. I can make animals do what I want them to do without training them. I can make bad things happen to people who annoy me. I can make them hurt if I want.",
	"Voldemort is my past, present, and future.",
	"Harry Potter, the Boy who Lived... come to die. Avada Kedavra!",
	"Invite him inside, Wormtail. Where are your manners?",
	"There is no good and evil, there is only power and those too weak to seek it.",
	"Welcome, my friends. Thirteen years it's been, and yet, here you stand before me, as though it were only yesterday. I confess myself... disappointed. Not one of you tried to find me.",
	"But I was willing to embrace mortal life again, before chasing immortality.",
	"I’m going to kill you, Harry Potter. I’m going to destroy you. After tonight, no one will ever again question my power. After tonight if they speak of you, they’ll only speak of how you begged for death. And how I being a merciful Lord… obliged.",
	"You’re a fool, Harry Potter, and you will lose everything.",
	"I have seen your heart and it's mine. I have seen your dreams, Ronald Weasley, and I have seen your fears...",
	"How is it that you - a skinny boy with no extraordinary magical talent - managed to defeat the greatest wizard of all time? How did you escape with nothing but a scar, while Lord Voldemort's powers were destroyed?",
	"The Boy who Lived. How lies have fed your legend, Harry! Shall I reveal what really happened that night thirteen years ago? Shall I divulge how I truly lost my powers? [Whispers] Yes, shall I?",
	"I was ripped from my body, I was less than spirit, less than the meanest ghost... but still, I was alive.",
	"Don't you turn your back on me, Harry Potter! I want you to look at me when I kill you! I want to see the light leave your eyes!",
	"The boy has discovered our secret, Nagini. It makes us vulnerable. We must deploy all our forces now to find him. And you, my friend, must stay close.",
	"Give me Harry Potter. Do this and none shall be harmed. Give me Harry Potter, and I shall leave Hogwarts untouched. Give me Harry Potter, and you will be rewarded. You have one hour.",
	"Harry. Ah, I'd almost forgotten you were here. Standing on the bones of my father. I'd introduce you but word has it you're almost as famous as me these days.",
	"Every drop of magical blood spilled is a terrible waste.",
	"Come out, Harry... come out and play, then it will be quick it might even be painless I would not know I have never died.",
	"We are joined tonight by Ms. Charity Burbage, who until recently taught at Hogwarts School of Witchcraft and Wizardry. Her specialty was Muggle Studies. It is Ms. Burbage's belief that Muggles are not so different from us... To her, the mixture of magical and Muggle blood is not an abomination, but something to be encouraged.",
	"As inspiring as I find your bloodlust, Bellatrix, I must be the one to kill Harry Potter.",
	"Pick up your wand, Potter! You've been taught how to duel, I presume. First, we bow to each other... Dumbledore wouldn't want you to forget your manners, would he?",
	"And here we have six missing Death Eaters... three dead in my service. One, too cowardly to return... he will pay. One, who I believe has left me for ever... he will be killed, of course... and one who remains my most faithful servant, and who has already re-entered my service.”",
	"Everyone thinks I'm special ... All those people in the Leaky Cauldron, Professor Quirrell, Mr. Ollivander ... But I don't know anything about magic at all.",
	"You're worth twelve of Malfoy. The Sorting Hat chose you for Gryffindor, didn't it? And where's Malfoy? In stinking Slytherin.",
	"The poor toilet's never had anything as horrible as your head down it—it might be sick.",
	"You've forgotten the magic word.",
	"I don't want to be rude or anything, but—this isn't a great time for me to have a house elf in my bedroom.",
	"And I thought I had it bad staying here for another four weeks,",
	"This makes the Dursleys sound almost human. Can't anyone help you? Can't I?",
	"Proud? Are you crazy? All those times I could have died and didn't manage it? They'll be furious ... ",
	"Yeah, you can have a word. Goodbye.",
	"I don't know who Maxime thinks she's kidding. If Hagrid's half-giant, she definitely is. Big bones ... the only things that's got bigger bones than her is a dinosaur.",
	"We could all do with a few laughs. I've got a feeling we're going to need them more than usual before long.",
	"Why do they have to move in packs? How're you supposed to get one on their own to ask them?",
	"My eyes aren't glistening with the ghosts of my past!",
	"Not as stupid as you look, are you, Dud? But I s'pose, if you were, you wouldn't be able to walk and talk at the same time.",
	"Wow, I wonder what it'd be like to have a difficult life?",
	"Quirrell was a great teacher, there was just that minor drawback of him having Lord Voldemort sticking out of the back of his head.",
	"Did he say you look like a pig that's been taught to walk on its hind legs? 'Cause that's not cheek, Dud, that's true.",
	"This is night, Diddykins. That's what we call it when it goes all dark like this.",
	"Hermione, you're good on feelings and stuff, but you just don't understand about Quidditch.",
	"You're the one who is weak. You will never know love or friendship. And I feel sorry for you.",
	"What d'you mean I'm not brave in bed?",
	"His priority did not seem to be to teach them what he knew, but rather to impress upon them that nothing, not even ... knowledge, was foolproof.",
	"So that's it, is it? Stay there? That's all anyone could tell me after I got attacked by those dementors too! Just stay put while the grown-ups sort it out, Harry! We won't bother telling you anything, though, because your tiny little brain might not be able to cope with it!",
	"Does anyone really know what You-Know-Who would or wouldn't do?",
	"One of the only honest things you've said to me. You don't care whether I live or die, but you do care that I help you convince everyone you're winning the war against Voldemort.",
	"He will only be gone from the school when none here are loyal to him.",
	"There's no need to call me 'sir,' Professor.",
	"Be brave, Professor. Be brave like my mother ... Otherwise, you disgrace her. Otherwise, she died for nothing. Otherwise, the bowl will remain empty ... forever.",
	"Dudley, for the first time in your life, you're talking sense.",
	"I won't blast people out of my way just because they're there. That's Voldemort's job.",
	"Severus Snape wasn't yours. Snape was Dumbledore's, Dumbledore's from the moment you started hunting down my mother. And you never realised it, because of the thing you can't understand. You never saw Snape cast a Patronus, did you, Riddle?",
	"Are you out of your mind?. A plot to get this house? Are you actually as stupid as you look?",
	"Albus Severus, you were named for two headmasters of Hogwarts. One of them was a Slytherin and he was probably the bravest man I ever knew.",
	"Yeah,and she's seeing someone. Jealous type. Big bloke. You wouldn't want to cross him.",
	"Words are, in my not-so-humble opinion, our most inexhaustible source of magic. Capable of both inflicting injury, and remedying it.",
	"It does not do to dwell on dreams and forget to live.",
	"People find it far easier to forgive others for being wrong than being right.",
	"It is my belief that the truth is generally preferable to lies.",
	"While we may come from different places and speak in different tongues, our hearts beat as one.",
	"Numbing the pain for a while will make it worse when you finally feel it.",
	"Curiosity is not a sin, but we should exercise caution with our curiosity.",
	"I sometimes find, and I am sure you know the feeling, that I simply have too many thoughts and memories crammed into my mind.",
	"It matters not what someone is born, but what they grow to be.",
	"The truth: It is a beautiful and terrible thing, and should therefore be treated with caution.",
	"Youth can not know how age thinks and feels, but old men are guilty if they forget what it is to be young.",
	"It is the unknown we fear when we look upon death and darkness. Nothing more.",
	"To the well-organized mind, death is but the next great adventure.",
	"Where your treasure is, there your heart will be also.",
	"It is our choices, Harry, that show what we truly are, far more than our abilities.",
	"Perhaps those who are best suited to power are those who have never sought it.",
	"Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?",
	"Differences of habit and language are nothing at all if our aims are identical and our hearts are open.",
	"It is important to fight and fight again, and keep fighting, for only then can evil be kept at bay though never quite eradicated.",
	"The best of us sometimes eat our words.",
	"We must all face the choice between what is right, and what is easy.",
	"One can never have enough socks.",
	"Killing is not so easy as the innocent believe.",
	"Do not pity the dead, Harry. Pity the living and above all, those who live without love.",
	"You think the dead we loved truly ever leave us? You think we don't recall them more clearly in times of great trouble?",
	"We are only as strong as we are united, as weak as we are divided.",
	"As much money and life as you could want! The two things most human beings would choose above all — the trouble is, humans do have a knack of choosing precisely those things that are worst for them.",
	"Have you any idea how much tyrants fear the people they oppress? All of them realize that one day, amongst their many victims, there is sure to be one that rises against them and strikes back!",
	"Let us step out into the night and pursue that flighty temptress, adventure.",
	"We must try not to sink beneath our anguish ... but battle on.",
	"It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
	"For in dreams we enter a world that is entirely our own. Let them swim in the deepest ocean or glide over the highest cloud.",
	"This pain is part of being human. The fact that you can feel pain like this is your greatest strength.",
	"Music, a magic beyond all we do here!",
	"Happiness can be found, even in the darkest of times, if one only remembers to turn on the light."

];

const getRandomSentence = () => {
	const randomIndex = Math.floor(Math.random() * sentences.length);
	return sentences[randomIndex];
};

export default getRandomSentence;
